# Generated by Django 5.0.6 on 2024-06-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_birthday_customuser_gander'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gander',
            new_name='gender',
        ),
    ]
